name: 'Lupocps - Create Video'
description: 'Convert markdown files into narrated videos.'
author: 'lupocps <help@lupo.ai>'
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
